env:
 - CABALVER=1.22 GHCVER=7.8.4

before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER # see note about happy/alex
 - export PATH=$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
 - travis_retry cabal update
 - cabal install alex happy

install:
 - git clone https://github.com/kazu-yamamoto/unit-test-example
 - cd unit-test-example
 - cabal install --enable-tests --only-dependencies

script:
 - cabal configure --enable-tests
 - cabal build
 - cabal test
